[package]
name = "snakers"
version = "0.1.0"
edition = "2024"
default-run = "main"

[dependencies]
macroquad = "0.4.14"
rand = "0.9.1"
rand_distr = "0.5.1"
rayon = "1.8"
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
typetag = "0.2"
